#!/bin/bash
#-------------------SCRIPT VARIABLES-------------------#
ofed_version=""
configure_ofed_env_location=""
script_name="create_ofed_env"
clone_path=""

#------------------------MAIN--------------------------#
while [ ! -z "$1" ]
do
	if [[ $1 =~ ^[0-9]_[0-9]|[0-9]_[0-9]_[0-9]$ ]]
	then 
		ofed_version="$1"
		shift
		continue
	fi
	case "$1" in
		-f | --full-env)
		configure_ofed_env_location="$2"
		if [[ ! -f "$configure_ofed_env_location" ]]
		then
			echo "-E- ${configure_ofed_env_location} script does not exist"
			return 1	
		fi
		shift
		;;
		-p | --path)
			clone_path=$2
		shift
		;;

		-h | --help)
		echo "Usage: source {script_name} [options] MAJOR_MINOR
			
	use this script to build OFED environment.
	important: need to source this script for full functionality.
	run this script as USER.

		-h, --help 		display this help message and exit
		-f, --full-env		make and configure full OFED enviroment without the abillty for cherry-pick
		-p, --path		directory path where OFED clone to
"
		return 1
		;;
		*)
		echo "-E- Unsupported option: $1" >&2
		echo "use -h flag to display help menu" 
		return 1
		;;
	esac
	shift
done
if [ -z "$ofed_version" ]
then
	echo "-E- must get version argument [MAJOR_MINOR]"
	return 1
fi
my_user=$(whoami)

echo "starting..."
if [ -z "$clone_path" ]
then
	cd /var/tmp
	rm -rf ${my_user}_OFED_${ofed_version}
	mkdir ${my_user}_OFED_${ofed_version}
	chown ${my_user} ${my_user}_OFED_${ofed_version} 
	cd ${my_user}_OFED_${ofed_version}
else
	cd ${clone_path}
fi
git clone ssh://${my_user}@l-gerrit.mtl.labs.mlnx:29418/mlnx_ofed/mlnx-ofa_kernel-4.0 && scp -p -P 29418 ${my_user}@l-gerrit.mtl.labs.mlnx:hooks/commit-msg mlnx-ofa_kernel-4.0/.git/hooks/
cd mlnx-ofa_kernel-4.0
git checkout -b ofed_${ofed_version} origin/mlnx_ofed_${ofed_version}
echo "inside ${PWD} directory"
echo "creating links..."
ln -s ofed_scripts/configure
ln -s ofed_scripts/makefile 
ln -s ofed_scripts/Makefile 
echo "finished creating ofed environment"
echo "----------------------------------"
if [ -z "$configure_ofed_env_location" ]
then	
	echo ""
	echo "you can cherry-pick required commits and run '/swgwork/royno/OFED/my_scripts/configure_ofed_env'"
	echo ""
else
	echo ""
	echo "executing ${configure_ofed_env_location}"
	echo ""
	source ${configure_ofed_env_location}
fi


